language: ruby
cache: bundler
before_install:
  - gem install bundler
rvm:
  - 2.3
  - 2.4
  - ruby-head
  - jruby-23mode
  - jruby-head
  - rubinius-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-23mode
    - rvm: rubinius-3
  fast_finish: true
